;;;; cl-cc-php.asd — PHP frontend: lexer, parser, grammar

(asdf:defsystem :cl-cc-php
  :description "CL-CC PHP frontend: lexer, parser, and grammar"
  :author "takeokunn"
  :license "MIT"
  :version "0.1.0"
  :depends-on (:cl-cc-ast :cl-cc-bootstrap :cl-cc-parse :cl-cc-vm)
  :pathname "src"
  :serial t
  :components
  ((:file "package")
   (:file "lexer")
   (:file "lexer-ops")
    (:file "runtime-helpers")
    (:file "runtime-helpers-array")
    (:file "runtime-constants")
    ;; PHP runtime builtins (count, array_*, str*, math, type predicates, and the
    ;; dispatch registry). Previously omitted, so their bodies were never compiled
    ;; — runtime calls such as array_find -> %php-array-pairs / %php-callable-function
    ;; hit undefined functions. register loads last (it references the others).
    (:file "runtime-builtins-core")
    (:file "runtime-builtins-array")
    (:file "runtime-builtins-array-sort")
    (:file "runtime-builtins-string-data")
    (:file "runtime-builtins-string")
    (:file "runtime-builtins-string-core")
    (:file "runtime-builtins-string-format")
    (:file "runtime-builtins-string-multibyte")
    (:file "runtime-builtins-string-encoding")
    (:file "runtime-builtins-string-transform")
    (:file "runtime-builtins-string-analysis")
    (:file "runtime-builtins-string-ctype")
    (:file "runtime-builtins-string-extra")
    (:file "runtime-builtins-string-serialization")
    (:file "runtime-builtins-string-json")
     (:file "runtime-builtins-string-digest")
     (:file "runtime-builtins-regex")
     (:file "runtime-builtins-regex-preg")
     (:file "runtime-builtins-regex-date")
     (:file "runtime-builtins-regex-number")
     (:file "runtime-builtins-regex-callback")
     (:file "runtime-builtins-regex-array")
     (:file "runtime-builtins-math")
     (:file "runtime-builtins-types")
     (:file "runtime-builtins-io-data")
     (:file "runtime-builtins-io")
     (:file "runtime-builtins-io-scan")
     (:file "runtime-builtins-io-files")
     (:file "runtime-builtins-io-objects")
     (:file "runtime-builtins-io-spl")
     (:file "runtime-builtins-io-reflection-objects")
     (:file "runtime-builtins-io-compat-objects")
     (:file "runtime-builtins-io-image")
     (:file "runtime-builtins-io-output")
     (:file "runtime-builtins-io-cookie-session")
     (:file "runtime-builtins-io-tokenizer")
     (:file "runtime-builtins-io-uri")
     (:file "runtime-builtins-register")
     (:file "parser")
      (:file "parser-support")
      (:file "parser-attributes")
      (:file "parser-expr")
      (:file "parser-expr-primary")
      (:file "parser-expr-new")
      (:file "parser-expr-postfix")
      (:file "parser-expr-operator")
      (:file "parser-expr-advanced")
     (:file "parser-expr-advanced-core")
     (:file "parser-expr-advanced-string")
     (:file "parser-expr-advanced-calls")
     (:file "parser-expr-advanced-short-circuit")
     (:file "parser-expr-advanced-closures")
     (:file "parser-expr-advanced-yield")
     (:file "parser-expr-advanced-array")
     (:file "parser-expr-advanced-match")
     (:file "parser-expr-advanced-compound")
     (:file "parser-expr-advanced-skip")
     (:file "parser-expr-advanced-dispatch")
   (:file "parser-stmt-lowering")
   (:file "parser-stmt-decls")
    (:file "parser-attribute-passes")
    (:file "parser-class")
    (:file "parser-trait")
    (:file "parser-interface")
    (:file "php84-features")
    (:file "unsupported")
    (:file "grammar")
   (:file "grammar-stmt")
   ;; Registers PHP's %PHP-* helpers as a backend bridge provider. Must load
   ;; last, after every %PHP-* function is defined.
   (:file "runtime-bridge-provider")))
