;;;; PHP tokenizer runtime builtins.

(in-package :cl-cc/php)

(defun %php-token-id (name)
  (%php-lookup-constant name))

(defun %php-token-entry (name text line)
  (multiple-value-bind (id found) (%php-token-id name)
    (declare (ignore found))
    (let ((entry (%php-make-array)))
      (%php-array-set entry 0 id)
      (%php-array-set entry 1 text)
      (%php-array-set entry 2 line)
      entry)))

(defun %php-token-name (token)
  (let ((id (%php-to-integer token)))
    (or (loop for name in +php-tokenizer-token-names+
              for value = (multiple-value-bind (constant found)
                              (%php-token-id name)
                            (and found constant))
              when (and value (= id value))
                do (return name))
        "UNKNOWN")))

(defun %php-token-get-all (source &optional flags)
  (let* ((code (%php-stringify source))
         (len (length code))
         (tokens (%php-make-array))
         (i 0)
         (line 1)
         (in-php nil)
         (token-parse-p (not (zerop (logand (%php-to-integer flags) 1))))
         (last-significant-token nil))
    (labels ((push-value (value)
               (%php-array-set tokens (%php-array-next-auto-index tokens) value))
             (newline-count (text)
               (loop for ch across text
                     count (char= ch #\Newline)))
             (advance-line (text)
               (incf line (newline-count text)))
             (significant-token-p (name)
               (not (member name '("T_WHITESPACE" "T_COMMENT" "T_DOC_COMMENT"
                                   "T_OPEN_TAG" "T_OPEN_TAG_WITH_ECHO"
                                   "T_CLOSE_TAG" "T_INLINE_HTML")
                            :test #'string=)))
             (record-significant-token (name)
               (when (significant-token-p name)
                 (setf last-significant-token name)))
             (emit-token (name text token-line)
               (push-value (%php-token-entry name text token-line))
               (record-significant-token name)
               (advance-line text))
             (emit-string (text)
               (push-value text)
               (setf last-significant-token text)
               (advance-line text))
             (starts-with-at-p (needle pos &key ignore-case)
               (let ((end-pos (+ pos (length needle))))
                 (and (<= end-pos len)
                      (if ignore-case
                          (string-equal needle code :start2 pos :end2 end-pos)
                          (string= needle code :start2 pos :end2 end-pos)))))
             (starts-with-p (needle &key ignore-case)
               (starts-with-at-p needle i :ignore-case ignore-case))
             (php-open-tag-p (pos)
               (or (starts-with-at-p "<?=" pos)
                   (starts-with-at-p "<?php" pos :ignore-case t)
                   (starts-with-at-p "<?" pos)))
             (scan-inline-html-end ()
               (let ((pos i))
                 (loop while (and (< pos len)
                                  (not (php-open-tag-p pos)))
                       do (incf pos))
                 pos))
             (identifier-start-p (ch)
               (or (alpha-char-p ch) (char= ch #\_)))
             (identifier-part-p (ch)
               (or (identifier-start-p ch) (digit-char-p ch)))
             (qualified-name-tail-end-position (pos)
               (let ((cursor pos)
                     (saw-tail nil))
                 (loop while (and (< cursor len)
                                  (char= (char code cursor) #\\)
                                  (< (1+ cursor) len)
                                  (identifier-start-p (char code (1+ cursor))))
                       do (setf saw-tail t)
                          (incf cursor 2)
                          (loop while (and (< cursor len)
                                           (identifier-part-p (char code cursor)))
                                do (incf cursor)))
                 (and saw-tail cursor)))
             (whitespace-p (ch)
               (member ch '(#\Space #\Tab #\Newline #\Return) :test #'char=))
             (scan-open-tag-text (base-length)
               (let ((start i)
                     (end (+ i base-length)))
                 (loop while (and (< end len)
                                  (whitespace-p (char code end)))
                       do (incf end))
                 (setf i end)
                 (subseq code start end)))
             (scan-while (predicate)
               (loop while (and (< i len)
                                (funcall predicate (char code i)))
                     do (incf i)))
             (scan-block-comment ()
               (let ((start i))
                 (incf i 2)
                 (loop while (< i len)
                       do (if (and (< (1+ i) len)
                                   (char= (char code i) #\*)
                                   (char= (char code (1+ i)) #\/))
                              (progn
                                (incf i 2)
                                (return))
                              (incf i)))
                 (subseq code start i)))
             (scan-quoted-string ()
               (let ((start i)
                     (quote (char code i)))
                 (incf i)
                 (loop while (< i len)
                       for ch = (char code i)
                       do (cond
                            ((char= ch #\\)
                             (incf i (if (< (1+ i) len) 2 1)))
                            ((char= ch quote)
                             (incf i)
                             (return))
                            (t
                             (incf i))))
                 (subseq code start i)))
             (close-tag-text ()
               (let ((end (+ i 2)))
                  (when (< end len)
                   (let ((next (char code end)))
                     (cond
                       ((and (char= next #\Return)
                             (< (1+ end) len)
                             (char= (char code (1+ end)) #\Newline))
                        (incf end 2))
                       ((or (char= next #\Return)
                            (char= next #\Newline))
                        (incf end)))))
                  (subseq code i end)))
             (yield-from-end-position (yield-end)
               (let ((pos yield-end))
                 (loop while (and (< pos len)
                                  (whitespace-p (char code pos)))
                       do (incf pos))
                 (let ((from-end (+ pos 4)))
                   (when (and (< yield-end pos)
                              (<= from-end len)
                              (string-equal "from" code :start2 pos :end2 from-end)
                              (or (= from-end len)
                                  (not (identifier-part-p (char code from-end)))))
                     from-end))))
             (keyword-token-name (text)
               (cdr (assoc (string-downcase text)
                           '(("echo" . "T_ECHO")
                             ("abstract" . "T_ABSTRACT")
                             ("array" . "T_ARRAY")
                             ("as" . "T_AS")
                             ("break" . "T_BREAK")
                             ("callable" . "T_CALLABLE")
                             ("case" . "T_CASE")
                             ("catch" . "T_CATCH")
                             ("class" . "T_CLASS")
                             ("const" . "T_CONST")
                             ("clone" . "T_CLONE")
                             ("continue" . "T_CONTINUE")
                             ("declare" . "T_DECLARE")
                             ("default" . "T_DEFAULT")
                             ("die" . "T_EXIT")
                             ("do" . "T_DO")
                             ("else" . "T_ELSE")
                             ("elseif" . "T_ELSEIF")
                             ("empty" . "T_EMPTY")
                             ("enddeclare" . "T_ENDDECLARE")
                             ("endfor" . "T_ENDFOR")
                             ("endforeach" . "T_ENDFOREACH")
                             ("endif" . "T_ENDIF")
                             ("endswitch" . "T_ENDSWITCH")
                             ("endwhile" . "T_ENDWHILE")
                             ("enum" . "T_ENUM")
                             ("eval" . "T_EVAL")
                             ("exit" . "T_EXIT")
                             ("extends" . "T_EXTENDS")
                             ("final" . "T_FINAL")
                             ("finally" . "T_FINALLY")
                             ("fn" . "T_FN")
                             ("for" . "T_FOR")
                             ("foreach" . "T_FOREACH")
                             ("public" . "T_PUBLIC")
                             ("function" . "T_FUNCTION")
                             ("global" . "T_GLOBAL")
                             ("goto" . "T_GOTO")
                             ("if" . "T_IF")
                             ("implements" . "T_IMPLEMENTS")
                             ("include" . "T_INCLUDE")
                             ("include_once" . "T_INCLUDE_ONCE")
                             ("instanceof" . "T_INSTANCEOF")
                             ("insteadof" . "T_INSTEADOF")
                             ("interface" . "T_INTERFACE")
                             ("isset" . "T_ISSET")
                             ("list" . "T_LIST")
                             ("match" . "T_MATCH")
                             ("namespace" . "T_NAMESPACE")
                             ("new" . "T_NEW")
                             ("print" . "T_PRINT")
                             ("private" . "T_PRIVATE")
                             ("protected" . "T_PROTECTED")
                             ("readonly" . "T_READONLY")
                             ("require" . "T_REQUIRE")
                             ("require_once" . "T_REQUIRE_ONCE")
                             ("return" . "T_RETURN")
                             ("static" . "T_STATIC")
                             ("switch" . "T_SWITCH")
                             ("throw" . "T_THROW")
                             ("trait" . "T_TRAIT")
                             ("try" . "T_TRY")
                             ("unset" . "T_UNSET")
                             ("use" . "T_USE")
                             ("var" . "T_VAR")
                             ("while" . "T_WHILE")
                             ("yield" . "T_YIELD")
                             ("and" . "T_LOGICAL_AND")
                             ("or" . "T_LOGICAL_OR")
                             ("xor" . "T_LOGICAL_XOR"))
                           :test #'string=)))
             (identifier-token-name (text)
               (if (and token-parse-p
                        (string= last-significant-token "T_CONST"))
                   "T_STRING"
                   (or (keyword-token-name text) "T_STRING"))))
      (loop while (< i len)
            do (let ((token-line line)
                     (ch (char code i)))
                 (if (not in-php)
                     (cond
                       ((starts-with-p "<?=")
                        (emit-token "T_OPEN_TAG_WITH_ECHO" "<?=" token-line)
                        (incf i 3)
                        (setf in-php t))
                       ((starts-with-p "<?php" :ignore-case t)
                        (emit-token "T_OPEN_TAG" (scan-open-tag-text 5) token-line)
                        (setf in-php t))
                       ((starts-with-p "<?")
                        (emit-token "T_OPEN_TAG" (scan-open-tag-text 2) token-line)
                        (setf in-php t))
                       (t
                        (let ((end (scan-inline-html-end)))
                          (emit-token "T_INLINE_HTML" (subseq code i end) token-line)
                          (setf i end))))
                     (cond
                       ((starts-with-p "?>")
                        (let ((text (close-tag-text)))
                          (emit-token "T_CLOSE_TAG" text token-line)
                          (incf i (length text))
                          (setf in-php nil)))
                       ((whitespace-p ch)
                        (let ((start i))
                          (scan-while #'whitespace-p)
                          (emit-token "T_WHITESPACE" (subseq code start i) token-line)))
                       ((starts-with-p "#[")
                        (emit-token "T_ATTRIBUTE" "#[" token-line)
                        (incf i 2))
                       ((or (starts-with-p "//") (char= ch #\#))
                        (let ((start i))
                          (incf i (if (char= ch #\#) 1 2))
                          (loop while (and (< i len)
                                           (not (char= (char code i) #\Newline)))
                                do (incf i))
                          (emit-token "T_COMMENT" (subseq code start i) token-line)))
                       ((starts-with-p "/*")
                        (emit-token (if (starts-with-p "/**") "T_DOC_COMMENT" "T_COMMENT")
                                    (scan-block-comment)
                                    token-line))
                       ((and (char= ch #\$)
                             (< (1+ i) len)
                             (identifier-start-p (char code (1+ i))))
                        (let ((start i))
                          (incf i)
                          (scan-while #'identifier-part-p)
                          (emit-token "T_VARIABLE" (subseq code start i) token-line)))
                       ((char= ch #\\)
                        (let ((start i))
                          (incf i)
                          (if (and (< i len) (identifier-start-p (char code i)))
                              (progn
                                (scan-while #'identifier-part-p)
                                (let ((qualified-end (qualified-name-tail-end-position i)))
                                  (when qualified-end
                                    (setf i qualified-end)))
                                (emit-token "T_NAME_FULLY_QUALIFIED" (subseq code start i) token-line))
                              (emit-token "T_NS_SEPARATOR" "\\" token-line))))
                       ((starts-with-p "(void)" :ignore-case t)
                        (let ((text (subseq code i (+ i 6))))
                          (emit-token "T_VOID_CAST" text token-line)
                          (incf i 6)))
                       ((starts-with-p "|>")
                        (emit-token "T_PIPE" "|>" token-line)
                        (incf i 2))
                       ((starts-with-p "->")
                        (emit-token "T_OBJECT_OPERATOR" "->" token-line)
                        (incf i 2))
                       ((starts-with-p "::")
                        (emit-token "T_DOUBLE_COLON" "::" token-line)
                        (incf i 2))
                       ((starts-with-p "=>")
                        (emit-token "T_DOUBLE_ARROW" "=>" token-line)
                        (incf i 2))
                       ((identifier-start-p ch)
                        (let ((start i))
                          (scan-while #'identifier-part-p)
                          (let* ((text (subseq code start i))
                                 (qualified-end (qualified-name-tail-end-position i))
                                 (yield-from-end (and (string-equal text "yield")
                                                      (yield-from-end-position i))))
                            (cond
                              ((and (string-equal text "namespace") qualified-end)
                               (setf i qualified-end)
                               (emit-token "T_NAME_RELATIVE" (subseq code start i) token-line))
                              (qualified-end
                               (setf i qualified-end)
                               (emit-token "T_NAME_QUALIFIED" (subseq code start i) token-line))
                              (yield-from-end
                               (let ((combined (subseq code start yield-from-end)))
                                 (setf i yield-from-end)
                                 (emit-token "T_YIELD_FROM" combined token-line)))
                              (t
                               (let ((token-name (identifier-token-name text)))
                                 (emit-token token-name text token-line)))))))
                       ((digit-char-p ch)
                        (let ((start i)
                              (has-dot nil))
                          (scan-while #'digit-char-p)
                          (when (and (< i len)
                                     (char= (char code i) #\.)
                                     (< (1+ i) len)
                                     (digit-char-p (char code (1+ i))))
                            (setf has-dot t)
                            (incf i)
                            (scan-while #'digit-char-p))
                          (emit-token (if has-dot "T_DNUMBER" "T_LNUMBER")
                                      (subseq code start i)
                                      token-line)))
                       ((or (char= ch #\') (char= ch #\"))
                        (emit-token "T_CONSTANT_ENCAPSED_STRING" (scan-quoted-string) token-line))
                       ((and (< (char-code ch) 32)
                             (not (member ch '(#\Tab #\Newline #\Return) :test #'char=)))
                        (emit-token "T_BAD_CHARACTER" (string ch) token-line)
                        (incf i))
                       (t
                        (emit-string (string ch))
                        (incf i)))))))
    tokens))
