;;;; runtime-builtins-register-names-late.lisp — PHP builtin name table
;;;; (second pass).
;;;;
;;;; Same shape as runtime-builtins-register-names.lisp, kept separate because
;;;; %php-register-all-builtins registers it AFTER seeding the by-reference
;;;; parameter registry. The division is positional, not thematic; do not merge
;;;; the two tables without checking what that seeding step reads.

(in-package :cl-cc/php)

(defparameter +php-builtin-name-table-2+
  ;; Registered after %PHP-SEED-BY-REF-PARAM-REGISTRY, same reasoning as above.
  '(
   ("get_debug_type" . %php-gettype)
   ;; array_is_list resolves through the symbol registry used by builtin dispatch.
   ;; File I/O.
   ("file_get_contents" . %php-file-get-contents)
   ("file_put_contents" . %php-file-put-contents)
   ("file" . %php-file)
   ("readfile" . %php-readfile)
   ("file_exists" . %php-file-exists)
   ("is_file" . %php-is-file)
   ("is_dir" . %php-is-dir)
   ("is_readable" . %php-is-readable)
   ("is_writable" . %php-is-writable)
   ("is_writeable" . %php-is-writeable)
   ("is_executable" . %php-is-executable)
   ("is_link" . %php-is-link)
   ("filesize" . %php-filesize)
   ("filemtime" . %php-filemtime)
   ("filetype" . %php-filetype)
   ("unlink" . %php-unlink)
   ("rename" . %php-rename)
   ("copy" . %php-copy)
   ("mkdir" . %php-mkdir)
   ("rmdir" . %php-rmdir)
   ("scandir" . %php-scandir)
   ("getcwd" . %php-getcwd)
   ("chdir" . %php-chdir)
   ("realpath" . %php-realpath)
   ("basename" . %php-basename)
   ("dirname" . %php-dirname)
   ("pathinfo" . %php-pathinfo)
   ("tempnam" . %php-tempnam)
   ("sys_get_temp_dir" . %php-sys-get-temp-dir)
   ("fopen" . %php-fopen)
   ("fclose" . %php-fclose)
   ("fread" . %php-fread)
   ("fwrite" . %php-fwrite)
   ("fputs" . %php-fputs)
   ("fgets" . %php-fgets)
   ("fgetc" . %php-fgetc)
   ("feof" . %php-feof)
   ("fflush" . %php-fflush)
   ("flock" . %php-flock)
   ("fseek" . %php-fseek)
   ("ftell" . %php-ftell)
   ("rewind" . %php-rewind)
   ("fgetcsv" . %php-fgetcsv)
   ("fputcsv" . %php-fputcsv)
   ;; System / environment.
   ("getenv" . %php-getenv)
   ("putenv" . %php-putenv)
   ("php_uname" . %php-php-uname)
   ("php_sapi_name" . %php-php-sapi-name)
   ("phpversion" . %php-php-version)
   ("ini_get" . %php-ini-get)
   ("ini_set" . %php-ini-set)
   ("get_error_handler" . %php-get-error-handler)
   ("set_error_handler" . %php-set-error-handler)
   ("restore_error_handler" . %php-restore-error-handler)
   ("get_exception_handler" . %php-get-exception-handler)
   ("restore_exception_handler" . %php-restore-exception-handler)
   ("error_reporting" . %php-error-reporting)
   ("gc_collect_cycles" . %php-gc-collect-cycles)
   ("opcache_is_script_cached_in_file_cache" . %php-opcache-is-script-cached-in-file-cache)
   ("curl_share_init_persistent" . %php-curl-share-init-persistent)
   ("curl_multi_get_handles" . %php-curl-multi-get-handles)
   ("enchant_dict_remove_from_session" . %php-enchant-dict-remove-from-session)
   ("enchant_dict_remove" . %php-enchant-dict-remove)
   ("pg_close_stmt" . %php-pg-close-stmt)
   ("pg_service" . %php-pg-service)
   ("trigger_error" . %php-trigger-error)
   ("user_error" . %php-trigger-error)
   ("exit" . %php-exit)
   ("die" . %php-die)
   ("sleep" . %php-sleep)
   ("usleep" . %php-usleep)
   ("nl_langinfo" . %php-nl-langinfo)
   ("locale_is_right_to_left" . %php-locale-is-right-to-left)
   ("ob_start" . %php-ob-start)
   ("ob_end_clean" . %php-ob-end-clean)
   ("ob_get_clean" . %php-ob-get-clean)
   ("ob_get_contents" . %php-ob-get-contents)
   ("http_response_code" . %php-http-response-code)
   ("header" . %php-header)
   ("headers_list" . %php-headers-list)
   ("headers_sent" . %php-headers-sent)
   ("mail" . %php-mail)
   ("setcookie" . %php-setcookie)
   ("setrawcookie" . %php-setrawcookie)
   ("session_name" . %php-session-name)
   ("session_id" . %php-session-id)
   ("session_set_cookie_params" . %php-session-set-cookie-params)
   ("session_get_cookie_params" . %php-session-get-cookie-params)
   ("session_start" . %php-session-start)
   ("scanf" . %php-scanf)
   ;; String misc.
   ("parse_str" . %php-parse-str)
   ("http_build_query" . %php-http-build-query)
   ;; Generators / iterators.
   ("iterator_to_array" . %php-iterator-to-array)
   ("iterator_count" . %php-iterator-count)
   ;; Class / OOP introspection.
   ("class_exists" . %php-class-exists)
   ("class_alias" . %php-class-alias)
   ("interface_exists" . %php-interface-exists)
   ("function_exists" . %php-function-exists)
   ("call_user_func" . %php-call-user-func)
   ("call_user_func_array" . %php-call-user-func-array)
   ("method_exists" . %php-method-exists)
   ("property_exists" . %php-property-exists)
   ("get_class" . %php-get-class)
   ("get_parent_class" . %php-get-parent-class)
   ("is_a" . %php-is-a)
   ("instanceof" . %php-instanceof)
   ("get_object_vars" . %php-get-object-vars)
   ("get_class_methods" . %php-get-class-methods)
   ;; Array extras.
   ("reset" . %php-reset)
   ("end" . %php-end)
   ("current" . %php-current)
   ("next" . %php-next)
   ("prev" . %php-prev)
   ("key" . %php-key)
   ;; Output / misc.
   ("echo" . %php-echo)
   ("print" . %php-print)
   ;; Registered by symbol so builtin dispatch resolves directly to the helper.
   ("var_export" . %php-var-export)
   ("serialize" . %php-serialize)
   ("unserialize" . %php-unserialize)
   ;; Additional string utilities.
   ("sscanf" . %php-sscanf)
   ;; CSPRNG
   ("random_int" . %php-random-int)
   ("random_bytes" . %php-random-bytes)
   ;; gmp extension (maps to CL bignums)
   ("gmp_init" . %php-gmp-init)
   ("gmp_add" . %php-gmp-add)
   ("gmp_sub" . %php-gmp-sub)
   ("gmp_mul" . %php-gmp-mul)
   ("gmp_div_q" . %php-gmp-div-q)
   ("gmp_div" . %php-gmp-div-q)
   ("gmp_mod" . %php-gmp-mod)
   ("gmp_pow" . %php-gmp-pow)
   ("gmp_abs" . %php-gmp-abs)
   ("gmp_neg" . %php-gmp-neg)
   ("gmp_gcd" . %php-gmp-gcd)
   ("gmp_cmp" . %php-gmp-cmp)
   ("gmp_intval" . %php-gmp-intval)
   ("gmp_strval" . %php-gmp-strval)
   ("gmp_sqrt" . %php-gmp-sqrt)
   ("gmp_fact" . %php-gmp-fact)
   ;; bcmath extension
   ("bcadd" . %php-bcadd)
   ("bcsub" . %php-bcsub)
   ("bcmul" . %php-bcmul)
   ("bcdiv" . %php-bcdiv)
   ("bcpow" . %php-bcpow)
   ("bcmod" . %php-bcmod)
   ("bccomp" . %php-bccomp)
   ("bcscale" . %php-bcscale)
   ("bcsqrt" . %php-bcsqrt)
    )
  "PHP builtin name -> Common Lisp implementation symbol (second segment,
registered after %PHP-SEED-BY-REF-PARAM-REGISTRY — see +PHP-BUILTIN-NAME-TABLE+).")
