;;;; Central PHP builtin registry.

(in-package :cl-cc/php)

(defun %php-register-vm-runtime-callables ()
  (let ((installer cl-cc/bootstrap:*vm-runtime-callable-installer*))
    (when installer
      (funcall installer "PHP-CURRENT-CLOSURE" #'%php-current-closure)))
  (cl-cc/vm:vm-register-host-bridge
   '%php-current-closure
   (lambda (&rest args)
     (apply (cl-cc/vm::%vm-runtime-callable "PHP-CURRENT-CLOSURE") args))))

(defun %php-register-host-bridges ()
  "Register PHP-specific host bridge aliases that bypass VM instruction names."
  (cl-cc/vm:vm-register-host-bridge 'max #'%php-max)
  (cl-cc/vm:vm-register-host-bridge 'min #'%php-min))

(defparameter *php-builtin-registry* (make-hash-table :test #'equal)
  "Map lowercase PHP builtin names to Common Lisp helper functions.")

(defparameter *php-builtin-symbol-registry* (make-hash-table :test #'equal)
  "Map lowercase PHP builtin names to helper symbols for parser lowering.")

(defun %php-normalize-builtin-name (name)
  "Normalize PHP builtin NAME for case-insensitive lookup."
  (string-downcase (string name)))

(defun %php-register-builtin (name function)
  "Register PHP builtin NAME to FUNCTION and return FUNCTION."
  ;; FUNCTION may be a function object or a function designator symbol. The
  ;; public registry stores the resolved helper function, while a side registry
  ;; keeps the symbol for parser integrations that lower calls to helper vars.
  ;; (%php-register-builtin "strlen" '%php-strlen) => #<FUNCTION %PHP-STRLEN>
  (let* ((key (%php-normalize-builtin-name name))
         (symbol (and (symbolp function) function))
         (fn (if symbol (symbol-function symbol) function)))
    (setf (gethash key *php-builtin-registry*) fn)
    (when symbol
      (setf (gethash key *php-builtin-symbol-registry*) symbol))
    fn))

(eval-when (:load-toplevel :execute)
  (%php-register-host-bridges))

(defun %php-lookup-builtin (name)
  "Return the helper function registered for PHP builtin NAME, or NIL."
  ;; (%php-lookup-builtin "STRLEN") => #<FUNCTION %PHP-STRLEN>
  (gethash (%php-normalize-builtin-name name) *php-builtin-registry*))

(defun %php-lookup-builtin-symbol (name)
  "Return the helper symbol registered for PHP builtin NAME, or NIL."
  (gethash (%php-normalize-builtin-name name) *php-builtin-symbol-registry*))

(defparameter +php-builtin-name-table+
  ;; PHP builtin name -> Common Lisp implementation symbol, registered before
  ;; %PHP-SEED-BY-REF-PARAM-REGISTRY runs (that seeding call reads no state
  ;; this registry populates, but stays in its original relative position
  ;; below for behavior-preserving safety).
  '(
   ;; Core.
   ("count" . %php-count)
   ("sizeof" . %php-count)
   ("isset" . %php-isset)
   ("empty" . %php-empty)
   ("is_null" . %php-is-null)
   ("unset" . %php-unset)
   ("compact" . %php-compact)
   ("extract" . %php-extract)
   ("print_r" . %php-print-r)
   ("var_dump" . %php-var-dump)
   ("gettype" . %php-gettype)
   ("array_key_exists" . %php-builtin-array-key-exists)
   ;; String.
   ("strlen" . %php-strlen)
   ("strtolower" . %php-strtolower)
   ("strtoupper" . %php-strtoupper)
   ("str_replace" . %php-str-replace)
   ("str_ireplace" . %php-str-ireplace)
   ("substr" . %php-substr)
   ("trim" . %php-trim)
   ("ltrim" . %php-ltrim)
   ("rtrim" . %php-rtrim)
   ("explode" . %php-explode)
   ("implode" . %php-implode)
   ("join" . %php-join)
   ("strpos" . %php-strpos)
   ("stripos" . %php-stripos)
   ("strrpos" . %php-strrpos)
   ("str_contains" . %php-str-contains)
   ("str_starts_with" . %php-str-starts-with)
   ("str_ends_with" . %php-str-ends-with)
   ("strrev" . %php-strrev)
   ("str_repeat" . %php-str-repeat)
   ("sprintf" . %php-sprintf)
   ("htmlspecialchars" . %php-htmlspecialchars)
   ("str_pad" . %php-str-pad)
   ("str_split" . %php-str-split)
   ("substr_count" . %php-substr-count)
   ("substr_replace" . %php-substr-replace)
   ("ucfirst" . %php-ucfirst)
   ("lcfirst" . %php-lcfirst)
   ("ucwords" . %php-ucwords)
   ("ord" . %php-ord)
   ("chr" . %php-chr)
   ("bin2hex" . %php-bin2hex)
   ("hex2bin" . %php-hex2bin)
   ("strcmp" . %php-strcmp)
   ("strcasecmp" . %php-strcasecmp)
   ("strncmp" . %php-strncmp)
   ("strncasecmp" . %php-strncasecmp)
   ("strstr" . %php-strstr)
   ("stristr" . %php-stristr)
   ("strchr" . %php-strchr)
   ("str_word_count" . %php-str-word-count)
   ("levenshtein" . %php-levenshtein)
   ("grapheme_levenshtein" . %php-grapheme-levenshtein)
   ("similar_text" . %php-similar-text)
   ("soundex" . %php-soundex)
   ("printf" . %php-printf)
   ("vsprintf" . %php-vsprintf)
   ("vprintf" . %php-vprintf)
   ("nl2br" . %php-nl2br)
   ("wordwrap" . %php-wordwrap)
   ("chunk_split" . %php-chunk-split)
   ("html_entity_decode" . %php-html-entity-decode)
   ("strip_tags" . %php-strip-tags)
   ("addslashes" . %php-addslashes)
   ("stripslashes" . %php-stripslashes)
   ("base64_encode" . %php-base64-encode)
   ("base64_decode" . %php-base64-decode)
   ("md5" . %php-md5)
   ("sha1" . %php-sha1)
   ("crc32" . %php-crc32)
   ("urlencode" . %php-urlencode)
   ("urldecode" . %php-urldecode)
   ("rawurlencode" . %php-rawurlencode)
   ("rawurldecode" . %php-rawurldecode)
   ("json_encode" . %php-json-encode)
   ("json_decode" . %php-json-decode)
   ("mb_strlen" . %php-mb-strlen)
   ("mb_substr" . %php-mb-substr)
   ("mb_strtolower" . %php-mb-strtolower)
   ("mb_strtoupper" . %php-mb-strtoupper)
   ("mb_strpos" . %php-mb-strpos)
   ("mb_strrpos" . %php-mb-strrpos)
   ("mb_substr_count" . %php-mb-substr-count)
   ("mb_detect_encoding" . %php-mb-detect-encoding)
   ("mb_internal_encoding" . %php-mb-internal-encoding)
   ("mb_convert_encoding" . %php-mb-convert-encoding)
   ("mb_convert_case" . %php-mb-convert-case)
   ("mb_str_pad" . %php-mb-str-pad)
   ("mb_str_split" . %php-mb-str-split)
   ("str_getcsv" . %php-str-getcsv)
   ("mb_chr" . %php-mb-chr)
   ("mb_ord" . %php-mb-ord)
   ("mb_strimwidth" . %php-mb-strimwidth)
   ("mb_ereg" . %php-mb-ereg)
   ("mb_eregi" . %php-mb-eregi)
   ("mb_ereg_replace" . %php-mb-ereg-replace)
   ("mb_eregi_replace" . %php-mb-eregi-replace)
   ("mb_split" . %php-mb-split)
   ;; Additional string functions
   ("strtr" . %php-strtr)
   ("strpbrk" . %php-strpbrk)
   ("strspn" . %php-strspn)
   ("strcspn" . %php-strcspn)
   ("quotemeta" . %php-quotemeta)
   ("htmlentities" . %php-htmlentities)
   ("metaphone" . %php-metaphone)
   ;; HTML/encoding
   ("htmlspecialchars_decode" . %php-htmlspecialchars-decode)
   ("quoted_printable_encode" . %php-quoted-printable-encode)
   ("quoted_printable_decode" . %php-quoted-printable-decode)
   ;; JSON
   ("json_validate" . %php-json-validate)
   ;; ctype_* character classification
   ("ctype_alpha" . %php-ctype-alpha)
   ("ctype_digit" . %php-ctype-digit)
   ("ctype_alnum" . %php-ctype-alnum)
   ("ctype_space" . %php-ctype-space)
   ("ctype_upper" . %php-ctype-upper)
   ("ctype_lower" . %php-ctype-lower)
   ("ctype_punct" . %php-ctype-punct)
   ("ctype_graph" . %php-ctype-graph)
   ("ctype_print" . %php-ctype-print)
   ("ctype_xdigit" . %php-ctype-xdigit)
   ;; Type checks
   ("is_countable" . %php-is-countable)
   ;; Array.
   ("array_merge" . %php-array-merge)
   ("array_keys" . %php-array-keys)
   ("array_values" . %php-array-values)
   ("array_push" . %php-array-push)
   ("array_pop" . %php-array-pop)
   ("array_shift" . %php-array-shift)
   ("array_unshift" . %php-array-unshift)
   ("in_array" . %php-in-array)
   ("array_search" . %php-array-search)
   ("array_reverse" . %php-array-reverse)
   ("array_slice" . %php-array-slice)
   ("array_unique" . %php-array-unique)
   ("array_map" . %php-array-map)
   ("array_filter" . %php-array-filter)
   ("array_reduce" . %php-array-reduce)
   ("sort" . %php-sort)
   ("rsort" . %php-rsort)
   ("asort" . %php-asort)
   ("ksort" . %php-ksort)
   ("range" . %php-range)
   ("usort" . %php-usort)
   ("uasort" . %php-uasort)
   ("uksort" . %php-uksort)
   ("array_walk" . %php-array-walk)
   ("array_chunk" . %php-array-chunk)
   ("array_pad" . %php-array-pad)
   ("array_count_values" . %php-array-count-values)
   ("array_sum" . %php-array-sum)
   ("array_product" . %php-array-product)
   ("array_diff" . %php-array-diff)
   ("array_intersect" . %php-array-intersect)
   ("array_udiff" . %php-array-udiff)
   ("array_uintersect" . %php-array-uintersect)
   ("array_column" . %php-array-column)
   ("array_combine" . %php-array-combine)
   ("array_flip" . %php-array-flip)
   ("array_fill" . %php-array-fill)
   ("array_fill_keys" . %php-array-fill-keys)
   ("array_splice" . %php-array-splice)
   ("array_replace" . %php-array-replace)
   ("krsort" . %php-krsort)
   ("arsort" . %php-arsort)
   ("array_diff_key" . %php-array-diff-key)
   ("array_intersect_key" . %php-array-intersect-key)
   ("array_diff_assoc" . %php-array-diff-assoc)
   ("array_intersect_assoc" . %php-array-intersect-assoc)
   ("array_merge_recursive" . %php-array-merge-recursive)
   ("shuffle" . %php-shuffle)
   ("array_key_first" . %php-array-key-first)
   ("array_key_last" . %php-array-key-last)
   ("array_first" . %php-array-first)
   ("array_last" . %php-array-last)
   ("array_walk_recursive" . %php-array-walk-recursive)
   ("natsort" . %php-natsort)
   ("natcasesort" . %php-natcasesort)
   ("strnatcmp" . %php-strnatcmp)
   ("strnatcasecmp" . %php-strnatcasecmp)
   ;; Array sorts and extras.
   ("array_multisort" . %php-array-multisort)
   ;; list() — returns array for destructuring
   ("list" . %php-list-assign)
   ;; PHP 8.4 array functions.
   ("array_find" . %php-array-find)
   ("array_find_key" . %php-array-find-key)
   ("array_any" . %php-array-any)
   ("array_all" . %php-array-all)
   ;; PHP 8.1 Fiber builtins are registered in the late-loaded feature module.
   ;; after those functions are defined.
   ;; PHP Exception / Throwable helpers.
   ("set_exception_handler" . %php-set-exception-handler)
   ("class_implements" . %php-class-implements)
   ("class_parents" . %php-class-parents)
   ("class_uses" . %php-class-uses)
   ("spl_autoload_register" . %php-spl-autoload-register)
   ("spl_autoload_unregister" . %php-spl-autoload-unregister)
   ("spl_autoload_functions" . %php-spl-autoload-functions)
   ;; SPL data structures.
   ("SplStack" . %php-spl-stack)
   ("SplQueue" . %php-spl-queue)
   ("SplDoublyLinkedList" . %php-spl-doubly-linked-list)
   ("SplMinHeap" . %php-spl-min-heap)
   ("SplMaxHeap" . %php-spl-max-heap)
   ("SplFixedArray" . %php-spl-fixed-array)
   ;; Math.
   ("abs" . %php-abs)
   ("ceil" . %php-ceil)
   ("floor" . %php-floor)
   ("round" . %php-round)
   ("max" . %php-max)
   ("min" . %php-min)
   ("rand" . %php-rand)
   ("mt_rand" . %php-mt-rand)
   ("sqrt" . %php-sqrt)
   ("pow" . %php-pow)
   ("intdiv" . %php-intdiv)
   ("fdiv" . %php-fdiv)
   ("array_is_list" . %php-array-is-list)
   ("pi" . %php-pi)
   ("sin" . %php-sin)
   ("cos" . %php-cos)
   ("tan" . %php-tan)
   ("log" . %php-log)
   ("exp" . %php-exp)
   ("fmod" . %php-fmod)
   ("number_format" . %php-number-format)
   ("base_convert" . %php-base-convert)
   ("asin" . %php-asin)
   ("acos" . %php-acos)
   ("atan" . %php-atan)
   ("atan2" . %php-atan2)
   ("sinh" . %php-sinh)
   ("cosh" . %php-cosh)
   ("tanh" . %php-tanh)
   ("log10" . %php-log10)
   ("log2" . %php-log2)
   ("hypot" . %php-hypot)
   ("deg2rad" . %php-deg2rad)
   ("rad2deg" . %php-rad2deg)
   ("decbin" . %php-decbin)
   ("decoct" . %php-decoct)
   ("dechex" . %php-dechex)
   ("bindec" . %php-bindec)
   ("octdec" . %php-octdec)
   ("hexdec" . %php-hexdec)
   ("is_nan" . %php-is-nan)
   ("is_finite" . %php-is-finite)
   ("is_infinite" . %php-is-infinite)
   ("lcg_value" . %php-lcg-value)
   ("mt_srand" . %php-mt-srand)
   ("srand" . %php-srand)
   ;; Regex
   ("preg_match" . %php-preg-match)
   ("preg_match_all" . %php-preg-match-all)
   ("preg_replace" . %php-preg-replace)
   ("preg_split" . %php-preg-split)
   ("preg_quote" . %php-preg-quote)
   ("preg_replace_callback" . %php-preg-replace-callback)
   ("preg_replace_callback_array" . %php-preg-replace-callback-array)
   ;; Date/Time
   ("time" . %php-time)
   ("microtime" . %php-microtime)
   ("mktime" . %php-mktime)
   ("gmmktime" . %php-mktime)
   ("strtotime" . %php-strtotime)
   ("date" . %php-date)
   ("checkdate" . %php-checkdate)
   ("gmdate" . %php-gmdate)
   ("date_create" . %php-date-create)
   ("date_format" . %php-date-format)
   ("date_modify" . %php-date-modify)
   ("date_diff" . %php-date-diff)
   ("date_timestamp_get" . %php-date-timestamp)
   ("date_default_timezone_set" . %php-date-default-timezone-set)
   ("date_default_timezone_get" . %php-date-default-timezone-get)
   ;; Types and conversions.
   ("is_int" . %php-is-int)
   ("is_integer" . %php-is-integer)
   ("is_long" . %php-is-long)
   ("is_float" . %php-is-float)
   ("is_double" . %php-is-double)
   ("is_real" . %php-is-real)
   ("is_string" . %php-is-string)
   ("is_bool" . %php-is-bool)
   ("is_array" . %php-is-array)
   ("is_object" . %php-is-object)
   ("is_callable" . %php-is-callable)
   ("is_numeric" . %php-is-numeric)
   ("is_scalar" . %php-is-scalar)
   ("is_iterable" . %php-is-iterable)
   ("intval" . %php-intval)
   ("floatval" . %php-floatval)
   ("strval" . %php-strval)
   ("boolval" . %php-boolval)
   ("filter_var" . %php-filter-var)
   ("image_type_to_extension" . %php-image-type-to-extension)
   ("image_type_to_mime_type" . %php-image-type-to-mime-type)
   ("getimagesize" . %php-getimagesize)
   ("exif_imagetype" . %php-exif-imagetype)
   ("token_get_all" . %php-token-get-all)
   ("token_name" . %php-token-name)
   ("settype" . %php-settype)
    )
  "PHP builtin name -> Common Lisp implementation symbol.")

(defparameter +php-builtin-name-table-2+
  ;; Registered after %PHP-SEED-BY-REF-PARAM-REGISTRY, same reasoning as above.
  '(
   ("get_debug_type" . %php-gettype)
   ;; array_is_list resolves through the symbol registry used by builtin dispatch.
   ;; File I/O.
   ("file_get_contents" . %php-file-get-contents)
   ("file_put_contents" . %php-file-put-contents)
   ("file" . %php-file)
   ("readfile" . %php-readfile)
   ("file_exists" . %php-file-exists)
   ("is_file" . %php-is-file)
   ("is_dir" . %php-is-dir)
   ("is_readable" . %php-is-readable)
   ("is_writable" . %php-is-writable)
   ("is_writeable" . %php-is-writeable)
   ("is_executable" . %php-is-executable)
   ("is_link" . %php-is-link)
   ("filesize" . %php-filesize)
   ("filemtime" . %php-filemtime)
   ("filetype" . %php-filetype)
   ("unlink" . %php-unlink)
   ("rename" . %php-rename)
   ("copy" . %php-copy)
   ("mkdir" . %php-mkdir)
   ("rmdir" . %php-rmdir)
   ("scandir" . %php-scandir)
   ("getcwd" . %php-getcwd)
   ("chdir" . %php-chdir)
   ("realpath" . %php-realpath)
   ("basename" . %php-basename)
   ("dirname" . %php-dirname)
   ("pathinfo" . %php-pathinfo)
   ("tempnam" . %php-tempnam)
   ("sys_get_temp_dir" . %php-sys-get-temp-dir)
   ("fopen" . %php-fopen)
   ("fclose" . %php-fclose)
   ("fread" . %php-fread)
   ("fwrite" . %php-fwrite)
   ("fputs" . %php-fputs)
   ("fgets" . %php-fgets)
   ("fgetc" . %php-fgetc)
   ("feof" . %php-feof)
   ("fflush" . %php-fflush)
   ("flock" . %php-flock)
   ("fseek" . %php-fseek)
   ("ftell" . %php-ftell)
   ("rewind" . %php-rewind)
   ("fgetcsv" . %php-fgetcsv)
   ("fputcsv" . %php-fputcsv)
   ;; System / environment.
   ("getenv" . %php-getenv)
   ("putenv" . %php-putenv)
   ("php_uname" . %php-php-uname)
   ("php_sapi_name" . %php-php-sapi-name)
   ("phpversion" . %php-php-version)
   ("ini_get" . %php-ini-get)
   ("ini_set" . %php-ini-set)
   ("get_error_handler" . %php-get-error-handler)
   ("set_error_handler" . %php-set-error-handler)
   ("restore_error_handler" . %php-restore-error-handler)
   ("get_exception_handler" . %php-get-exception-handler)
   ("restore_exception_handler" . %php-restore-exception-handler)
   ("error_reporting" . %php-error-reporting)
   ("gc_collect_cycles" . %php-gc-collect-cycles)
   ("opcache_is_script_cached_in_file_cache" . %php-opcache-is-script-cached-in-file-cache)
   ("curl_share_init_persistent" . %php-curl-share-init-persistent)
   ("curl_multi_get_handles" . %php-curl-multi-get-handles)
   ("enchant_dict_remove_from_session" . %php-enchant-dict-remove-from-session)
   ("enchant_dict_remove" . %php-enchant-dict-remove)
   ("pg_close_stmt" . %php-pg-close-stmt)
   ("pg_service" . %php-pg-service)
   ("trigger_error" . %php-trigger-error)
   ("user_error" . %php-trigger-error)
   ("exit" . %php-exit)
   ("die" . %php-die)
   ("sleep" . %php-sleep)
   ("usleep" . %php-usleep)
   ("nl_langinfo" . %php-nl-langinfo)
   ("locale_is_right_to_left" . %php-locale-is-right-to-left)
   ("ob_start" . %php-ob-start)
   ("ob_end_clean" . %php-ob-end-clean)
   ("ob_get_clean" . %php-ob-get-clean)
   ("ob_get_contents" . %php-ob-get-contents)
   ("http_response_code" . %php-http-response-code)
   ("header" . %php-header)
   ("headers_list" . %php-headers-list)
   ("headers_sent" . %php-headers-sent)
   ("mail" . %php-mail)
   ("setcookie" . %php-setcookie)
   ("setrawcookie" . %php-setrawcookie)
   ("session_name" . %php-session-name)
   ("session_id" . %php-session-id)
   ("session_set_cookie_params" . %php-session-set-cookie-params)
   ("session_get_cookie_params" . %php-session-get-cookie-params)
   ("session_start" . %php-session-start)
   ("scanf" . %php-scanf)
   ;; String misc.
   ("parse_str" . %php-parse-str)
   ("http_build_query" . %php-http-build-query)
   ;; Generators / iterators.
   ("iterator_to_array" . %php-iterator-to-array)
   ("iterator_count" . %php-iterator-count)
   ;; Class / OOP introspection.
   ("class_exists" . %php-class-exists)
   ("class_alias" . %php-class-alias)
   ("interface_exists" . %php-interface-exists)
   ("function_exists" . %php-function-exists)
   ("call_user_func" . %php-call-user-func)
   ("call_user_func_array" . %php-call-user-func-array)
   ("method_exists" . %php-method-exists)
   ("property_exists" . %php-property-exists)
   ("get_class" . %php-get-class)
   ("get_parent_class" . %php-get-parent-class)
   ("is_a" . %php-is-a)
   ("instanceof" . %php-instanceof)
   ("get_object_vars" . %php-get-object-vars)
   ("get_class_methods" . %php-get-class-methods)
   ;; Array extras.
   ("reset" . %php-reset)
   ("end" . %php-end)
   ("current" . %php-current)
   ("next" . %php-next)
   ("prev" . %php-prev)
   ("key" . %php-key)
   ;; Output / misc.
   ("echo" . %php-echo)
   ("print" . %php-print)
   ;; Registered by symbol so builtin dispatch resolves directly to the helper.
   ("var_export" . %php-var-export)
   ("serialize" . %php-serialize)
   ("unserialize" . %php-unserialize)
   ;; Additional string utilities.
   ("sscanf" . %php-sscanf)
   ;; CSPRNG
   ("random_int" . %php-random-int)
   ("random_bytes" . %php-random-bytes)
   ;; gmp extension (maps to CL bignums)
   ("gmp_init" . %php-gmp-init)
   ("gmp_add" . %php-gmp-add)
   ("gmp_sub" . %php-gmp-sub)
   ("gmp_mul" . %php-gmp-mul)
   ("gmp_div_q" . %php-gmp-div-q)
   ("gmp_div" . %php-gmp-div-q)
   ("gmp_mod" . %php-gmp-mod)
   ("gmp_pow" . %php-gmp-pow)
   ("gmp_abs" . %php-gmp-abs)
   ("gmp_neg" . %php-gmp-neg)
   ("gmp_gcd" . %php-gmp-gcd)
   ("gmp_cmp" . %php-gmp-cmp)
   ("gmp_intval" . %php-gmp-intval)
   ("gmp_strval" . %php-gmp-strval)
   ("gmp_sqrt" . %php-gmp-sqrt)
   ("gmp_fact" . %php-gmp-fact)
   ;; bcmath extension
   ("bcadd" . %php-bcadd)
   ("bcsub" . %php-bcsub)
   ("bcmul" . %php-bcmul)
   ("bcdiv" . %php-bcdiv)
   ("bcpow" . %php-bcpow)
   ("bcmod" . %php-bcmod)
   ("bccomp" . %php-bccomp)
   ("bcscale" . %php-bcscale)
   ("bcsqrt" . %php-bcsqrt)
    )
  "PHP builtin name -> Common Lisp implementation symbol (second segment,
registered after %PHP-SEED-BY-REF-PARAM-REGISTRY — see +PHP-BUILTIN-NAME-TABLE+).")

(defun %php-register-all-builtins ()
  "Register all supported PHP builtin helpers and return the registry."
  ;; The registry intentionally includes common aliases such as sizeof/count,
  ;; join/implode, and is_integer/is_int.
  ;; (%php-register-all-builtins) => *PHP-BUILTIN-REGISTRY*
  (clrhash *php-builtin-registry*)
  (clrhash *php-builtin-symbol-registry*)
  (dolist (entry +php-builtin-name-table+)
    (%php-register-builtin (car entry) (cdr entry)))
  (%php-seed-by-ref-param-registry *php-by-ref-param-registry*)
  (dolist (entry +php-builtin-name-table-2+)
    (%php-register-builtin (car entry) (cdr entry)))
  *php-builtin-registry*)

(eval-when (:load-toplevel :execute)
  (export '(*php-builtin-registry*
            %php-register-builtin
            %php-lookup-builtin
            %php-register-all-builtins
            %php-lookup-builtin-symbol
            %php-array-pairs)
          :cl-cc/php)
  (setf cl-cc/bootstrap:*runtime-vm-callable-register-hook*
        #'%php-register-vm-runtime-callables)
  (%php-register-vm-runtime-callables)
  (%php-register-all-builtins))
