;;;; PHP runtime constants and predefined constant lookup.

(in-package :cl-cc/php)

;;; ─── Predefined constants ──────────────────────────────────────────────────
;;; PHP magic/predefined constants (PHP_EOL, M_PI, STR_PAD_LEFT, SORT_*, ...)
;;; are referenced bare, e.g. `echo PHP_EOL;` or
;;; `str_pad($s, 3, "0", STR_PAD_LEFT)`. The parser (php-parse-primary)
;;; consults this table and lowers a hit to a literal; a miss stays an ast-var
;;; so user define()/const values still resolve at runtime.
(defparameter +php-nl-langinfo-items+
  '(("CODESET" 1 "UTF-8")
    ("ABDAY_1" 2 "Sun") ("ABDAY_2" 3 "Mon") ("ABDAY_3" 4 "Tue")
    ("ABDAY_4" 5 "Wed") ("ABDAY_5" 6 "Thu") ("ABDAY_6" 7 "Fri")
    ("ABDAY_7" 8 "Sat")
    ("DAY_1" 9 "Sunday") ("DAY_2" 10 "Monday") ("DAY_3" 11 "Tuesday")
    ("DAY_4" 12 "Wednesday") ("DAY_5" 13 "Thursday")
    ("DAY_6" 14 "Friday") ("DAY_7" 15 "Saturday")
    ("ABMON_1" 16 "Jan") ("ABMON_2" 17 "Feb") ("ABMON_3" 18 "Mar")
    ("ABMON_4" 19 "Apr") ("ABMON_5" 20 "May") ("ABMON_6" 21 "Jun")
    ("ABMON_7" 22 "Jul") ("ABMON_8" 23 "Aug") ("ABMON_9" 24 "Sep")
    ("ABMON_10" 25 "Oct") ("ABMON_11" 26 "Nov") ("ABMON_12" 27 "Dec")
    ("MON_1" 28 "January") ("MON_2" 29 "February") ("MON_3" 30 "March")
    ("MON_4" 31 "April") ("MON_5" 32 "May") ("MON_6" 33 "June")
    ("MON_7" 34 "July") ("MON_8" 35 "August") ("MON_9" 36 "September")
    ("MON_10" 37 "October") ("MON_11" 38 "November") ("MON_12" 39 "December")
    ("AM_STR" 40 "AM") ("PM_STR" 41 "PM")
    ("D_T_FMT" 42 "%a %b %e %H:%M:%S %Y")
    ("D_FMT" 43 "%m/%d/%y")
    ("T_FMT" 44 "%H:%M:%S")
    ("T_FMT_AMPM" 45 "%I:%M:%S %p")
    ("ERA" 46 "") ("ERA_D_T_FMT" 47 "") ("ERA_D_FMT" 48 "")
    ("ERA_T_FMT" 49 "") ("ALT_DIGITS" 50 "")
    ("YESEXPR" 51 "^[yY]") ("NOEXPR" 52 "^[nN]")
    ("YESSTR" 53 "") ("NOSTR" 54 "")
    ("CRNCYSTR" 55 "") ("RADIXCHAR" 56 ".") ("THOUSEP" 57 ","))
  "Deterministic nl_langinfo item table used by PHP constants and runtime.")

(defparameter *php-predefined-constants*
  (let ((h (make-hash-table :test #'equal)))
    (flet ((c (name value) (setf (gethash name h) value)))
      ;; core
      (c "PHP_EOL" (string #\Newline))
      (c "PHP_INT_MAX" 9223372036854775807)
      (c "PHP_INT_MIN" -9223372036854775808)
      (c "PHP_INT_SIZE" 8)
      (c "PHP_FLOAT_MAX" most-positive-double-float)
      (c "PHP_FLOAT_MIN" least-positive-normalized-double-float)
      (c "PHP_FLOAT_EPSILON" 2.220446049250313d-16)
      (c "PHP_FLOAT_DIG" 15)
      (c "PHP_VERSION" "8.5.0")
      (c "PHP_VERSION_ID" 80500)
      (c "PHP_MAJOR_VERSION" 8)
      (c "PHP_MINOR_VERSION" 5)
      (c "PHP_RELEASE_VERSION" 0)
      (c "PHP_BUILD_DATE" "1970-01-01T00:00:00+00:00")
      (c "PHP_BUILD_PROVIDER" "cl-cc")
      (c "PHP_OS" "Linux")
      (c "PHP_OS_FAMILY" "Linux")
      (c "PHP_MAXPATHLEN" 4096)
      (c "PHP_SAPI" "cli")
      (c "DIRECTORY_SEPARATOR" "/")
      (c "PATH_SEPARATOR" ":")
      ;; cURL
      (c "CURLINFO_USED_PROXY" 2097280)
      (c "CURLINFO_HTTPAUTH_USED" 2097281)
      (c "CURLINFO_PROXYAUTH_USED" 2097282)
      (c "CURLINFO_CONN_ID" 2097283)
      (c "CURLINFO_QUEUE_TIME_T" 6291476)
      (c "CURLOPT_INFILESIZE_LARGE" 30115)
      (c "CURLOPT_SSL_SIGNATURE_ALGORITHMS" 10328)
      (c "CURLFOLLOW_ALL" 1)
      (c "CURLFOLLOW_OBEYCODE" 2)
      (c "CURLFOLLOW_FIRSTONLY" 3)
      ;; math
      (c "M_PI" pi)
      (c "M_E" (exp 1.0d0))
      (c "M_SQRT2" (sqrt 2.0d0))
      (c "M_SQRT3" (sqrt 3.0d0))
      (c "M_SQRT1_2" (/ 1.0d0 (sqrt 2.0d0)))
      (c "M_2_SQRTPI" (/ 2.0d0 (sqrt pi)))
      (c "M_1_PI" (/ 1.0d0 pi))
      (c "M_2_PI" (/ 2.0d0 pi))
      (c "M_PI_2" (/ pi 2))
      (c "M_PI_4" (/ pi 4))
      (c "M_LN2" (log 2.0d0))
      (c "M_LN10" (log 10.0d0))
      (c "M_LOG2E" (log (exp 1.0d0) 2.0d0))
      (c "M_LOG10E" (log (exp 1.0d0) 10.0d0))
      (c "M_EULER" 0.5772156649015329d0)
      (c "INF" most-positive-double-float)
      (c "NAN" #.(sb-kernel:make-double-float #x7FF80000 0))
      ;; error reporting
      (c "E_ALL" 32767) (c "E_ERROR" 1) (c "E_WARNING" 2) (c "E_NOTICE" 8)
      (c "E_STRICT" 2048) (c "E_DEPRECATED" 8192) (c "E_USER_ERROR" 256)
      (c "E_USER_WARNING" 512) (c "E_USER_NOTICE" 1024)
      ;; sort
      (c "SORT_REGULAR" 0) (c "SORT_NUMERIC" 1) (c "SORT_STRING" 2)
      (c "SORT_DESC" 3) (c "SORT_ASC" 4) (c "SORT_NATURAL" 6) (c "SORT_FLAG_CASE" 8)
      ;; count / array_filter
      (c "COUNT_NORMAL" 0) (c "COUNT_RECURSIVE" 1)
      (c "ARRAY_FILTER_USE_BOTH" 1) (c "ARRAY_FILTER_USE_KEY" 2)
      ;; filter
      (c "FILTER_DEFAULT" 516) (c "FILTER_UNSAFE_RAW" 516)
      (c "FILTER_VALIDATE_INT" 257) (c "FILTER_VALIDATE_BOOLEAN" 258)
      (c "FILTER_VALIDATE_FLOAT" 259)
      (c "FILTER_VALIDATE_URL" 273) (c "FILTER_VALIDATE_EMAIL" 274)
      (c "FILTER_NULL_ON_FAILURE" 134217728)
      (c "FILTER_THROW_ON_FAILURE" 268435456)
      ;; intl
      (c "DECIMAL_COMPACT_SHORT" 1)
      (c "DECIMAL_COMPACT_LONG" 2)
      ;; openssl
      (c "OPENSSL_PKCS1_PSS_PADDING" 6)
      (c "PKCS7_NOSMIMECAP" 512)
      (c "PKCS7_CRLFEOL" 2048)
      (c "PKCS7_NOCRL" 8192)
      (c "PKCS7_NO_DUAL_CONTENT" 16384)
      ;; posix
      (c "POSIX_SC_OPEN_MAX" 4)
      ;; sockets
      (c "IPPROTO_ICMP" 1)
      (c "IPPROTO_ICMPV6" 58)
      (c "TCP_FUNCTION_BLK" 0)
      (c "TCP_FUNCTION_ALIAS" 1)
      (c "TCP_REUSPORT_LB_NUMA" 1026)
      (c "TCP_REUSPORT_LB_NUMA_NODOM" 1027)
      (c "TCP_REUSPORT_LB_NUMA_CURDOM" 1028)
      (c "TCP_BBR_ALGORITHM" 4)
      (c "AF_PACKET" 17)
      (c "IP_BINDANY" 24)
      (c "SO_BUSY_POLL" 46)
      (c "UDP_SEGMENT" 103)
      (c "SHUT_RD" 0)
      (c "SHUT_WR" 1)
      (c "SHUT_RDWR" 2)
      ;; tokenizer
      (c "TOKEN_PARSE" 1)
      (c "T_LNUMBER" 260)
      (c "T_DNUMBER" 261)
      (c "T_STRING" 262)
      (c "T_VARIABLE" 266)
      (c "T_CONSTANT_ENCAPSED_STRING" 269)
      (c "T_OBJECT_OPERATOR" 388)
      (c "T_DOUBLE_ARROW" 390)
      (c "T_COMMENT" 391)
      (c "T_DOC_COMMENT" 392)
      (c "T_OPEN_TAG" 393)
      (c "T_OPEN_TAG_WITH_ECHO" 394)
      (c "T_CLOSE_TAG" 395)
      (c "T_WHITESPACE" 396)
      (c "T_DOUBLE_COLON" 401)
      (c "T_VOID_CAST" 402)
      (c "T_PIPE" 403)
      (c "T_INLINE_HTML" 404)
      (c "T_ECHO" 405)
      (c "T_CLASS" 406)
      (c "T_CONST" 407)
      (c "T_PUBLIC" 408)
      (c "T_FUNCTION" 409)
      (c "T_ABSTRACT" 410)
      (c "T_ARRAY" 411)
      (c "T_AS" 412)
      (c "T_BREAK" 413)
      (c "T_CALLABLE" 414)
      (c "T_CASE" 415)
      (c "T_CATCH" 416)
      (c "T_CLONE" 417)
      (c "T_CONTINUE" 418)
      (c "T_DECLARE" 419)
      (c "T_DEFAULT" 420)
      (c "T_DO" 421)
      (c "T_ELSE" 422)
      (c "T_ELSEIF" 423)
      (c "T_EMPTY" 424)
      (c "T_ENDDECLARE" 425)
      (c "T_ENDFOR" 426)
      (c "T_ENDFOREACH" 427)
      (c "T_ENDIF" 428)
      (c "T_ENDSWITCH" 429)
      (c "T_ENDWHILE" 430)
      (c "T_ENUM" 431)
      (c "T_EVAL" 432)
      (c "T_EXIT" 433)
      (c "T_EXTENDS" 434)
      (c "T_FINAL" 435)
      (c "T_FINALLY" 436)
      (c "T_FN" 437)
      (c "T_FOR" 438)
      (c "T_FOREACH" 439)
      (c "T_GLOBAL" 440)
      (c "T_GOTO" 441)
      (c "T_IF" 442)
      (c "T_IMPLEMENTS" 443)
      (c "T_INCLUDE" 444)
      (c "T_INCLUDE_ONCE" 445)
      (c "T_INSTANCEOF" 446)
      (c "T_INSTEADOF" 447)
      (c "T_INTERFACE" 448)
      (c "T_ISSET" 449)
      (c "T_LIST" 450)
      (c "T_MATCH" 451)
      (c "T_NAMESPACE" 452)
      (c "T_NEW" 453)
      (c "T_PRINT" 454)
      (c "T_PRIVATE" 455)
      (c "T_PROTECTED" 456)
      (c "T_READONLY" 457)
      (c "T_REQUIRE" 458)
      (c "T_REQUIRE_ONCE" 459)
      (c "T_RETURN" 460)
      (c "T_STATIC" 461)
      (c "T_SWITCH" 462)
      (c "T_THROW" 463)
      (c "T_TRAIT" 464)
      (c "T_TRY" 465)
      (c "T_UNSET" 466)
      (c "T_USE" 467)
      (c "T_VAR" 468)
      (c "T_WHILE" 469)
      (c "T_YIELD" 470)
      (c "T_LOGICAL_AND" 471)
      (c "T_LOGICAL_OR" 472)
      (c "T_LOGICAL_XOR" 473)
      (c "T_YIELD_FROM" 474)
      (c "T_ATTRIBUTE" 475)
      (c "T_NS_SEPARATOR" 476)
      (c "T_NAME_FULLY_QUALIFIED" 477)
      (c "T_NAME_QUALIFIED" 478)
      (c "T_NAME_RELATIVE" 479)
      (c "T_BAD_CHARACTER" 480)
      ;; standard
      (c "IMAGETYPE_UNKNOWN" 0)
      (c "IMAGETYPE_WEBP" 18)
      (c "IMAGETYPE_AVIF" 19)
      (c "IMAGETYPE_HEIF" 20)
      (c "IMAGETYPE_SVG" 21)
      (c "IMAGETYPE_COUNT" 22)
      ;; str_pad
      (c "STR_PAD_RIGHT" 1) (c "STR_PAD_LEFT" 0) (c "STR_PAD_BOTH" 2)
      ;; htmlspecialchars
      (c "ENT_HTML401" 0) (c "ENT_QUOTES" 3) (c "ENT_COMPAT" 2)
      (c "ENT_NOQUOTES" 0) (c "ENT_HTML5" 48)
      ;; json
      (c "JSON_PRETTY_PRINT" 128) (c "JSON_UNESCAPED_UNICODE" 256)
      (c "JSON_UNESCAPED_SLASHES" 64) (c "JSON_THROW_ON_ERROR" 4194304)
      (c "JSON_ERROR_NONE" 0) (c "JSON_HEX_TAG" 1)
      ;; filesystem
      (c "FILE_APPEND" 8) (c "FILE_USE_INCLUDE_PATH" 1)
      (c "FILE_IGNORE_NEW_LINES" 2) (c "FILE_SKIP_EMPTY_LINES" 4)
      (c "LOCK_SH" 1) (c "LOCK_EX" 2) (c "LOCK_UN" 3) (c "LOCK_NB" 4)
      (c "SEEK_SET" 0) (c "SEEK_CUR" 1) (c "SEEK_END" 2)
      ;; preg
      (c "PREG_SPLIT_NO_EMPTY" 1) (c "PREG_SPLIT_DELIM_CAPTURE" 2)
      (c "PREG_PATTERN_ORDER" 1) (c "PREG_SET_ORDER" 2) (c "PREG_OFFSET_CAPTURE" 256)
      ;; round modes
      (c "PHP_ROUND_HALF_UP" 1) (c "PHP_ROUND_HALF_DOWN" 2)
      (c "PHP_ROUND_HALF_EVEN" 3) (c "PHP_ROUND_HALF_ODD" 4)
      ;; locale / nl_langinfo
      (dolist (item +php-nl-langinfo-items+)
        (c (first item) (second item))))
    h)
  "Name (case-sensitive string) → value for PHP predefined constants.")

(defparameter *php-dynamic-predefined-constants*
  (let ((h (make-hash-table :test #'equal)))
    (flet ((c (name helper) (setf (gethash name h) helper)))
      (c "STDIN" '%php-stdin)
      (c "STDOUT" '%php-stdout)
      (c "STDERR" '%php-stderr))
    h)
  "Name (case-sensitive string) → zero-arg runtime helper symbol for dynamic
PHP predefined constants.")

(defun %php-lookup-dynamic-constant (name)
  "Return (values HELPER T) when NAME is a dynamic predefined PHP constant,
else (values NIL NIL)."
  (multiple-value-bind (helper found) (gethash name *php-dynamic-predefined-constants*)
    (if found
        (values helper t)
        (let ((sep (position (code-char 92) name :from-end t)))
          (if sep
              (gethash (subseq name (1+ sep)) *php-dynamic-predefined-constants*)
              (values nil nil))))))

(defun %php-lookup-constant (name)
  "Return (values VALUE T) when NAME is a predefined PHP constant, else
(values NIL NIL).  Tries NAME, then its unqualified tail (after the last \\) so
\\PHP_EOL and NS\\PHP_EOL resolve to the global constant."
  (multiple-value-bind (value found) (gethash name *php-predefined-constants*)
    (if found
        (values value t)
        (let ((sep (position (code-char 92) name :from-end t)))
          (if sep
              (gethash (subseq name (1+ sep)) *php-predefined-constants*)
              (values nil nil))))))

(defparameter *php-predefined-class-constants*
  (make-hash-table :test #'equal)
  "Class/constant-name pair to value for runtime-visible PHP class constants.")

(defun %php-class-constant-key (class-name constant-name)
  (cons (string-upcase (princ-to-string class-name))
        (string-upcase (princ-to-string constant-name))))

(defun %php-register-predefined-class-constant (class-name constant-name value)
  (setf (gethash (%php-class-constant-key class-name constant-name)
                 *php-predefined-class-constants*)
        value))

(defun %php-predefined-class-constant (class-name constant-name)
  "Return a predefined PHP class constant value or signal an undefined-constant error."
  (multiple-value-bind (value foundp)
      (gethash (%php-class-constant-key class-name constant-name)
               *php-predefined-class-constants*)
    (if foundp
        value
        (error "Undefined PHP class constant ~A::~A" class-name constant-name))))

(dolist (entry '(("IntlListFormatter" "TYPE_AND" 0)
                 ("IntlListFormatter" "TYPE_OR" 1)
                 ("IntlListFormatter" "TYPE_UNITS" 2)
                 ("IntlListFormatter" "WIDTH_WIDE" 0)
                 ("IntlListFormatter" "WIDTH_SHORT" 1)
                 ("IntlListFormatter" "WIDTH_NARROW" 2)
                 ("NumberFormatter" "CURRENCY_ISO" 10)
                 ("NumberFormatter" "CURRENCY_PLURAL" 11)
                 ("NumberFormatter" "CURRENCY_ACCOUNTING" 12)
                 ("NumberFormatter" "CASH_CURRENCY" 13)
                 ("NumberFormatter" "DECIMAL_COMPACT_SHORT" 14)
                 ("NumberFormatter" "DECIMAL_COMPACT_LONG" 15)
                 ("NumberFormatter" "CURRENCY_STANDARD" 16)
                 ("Pdo\\Sqlite" "ATTR_OPEN_FLAGS" 1000)
                 ("Pdo\\Sqlite" "OPEN_READONLY" 1)
                 ("Pdo\\Sqlite" "OPEN_READWRITE" 2)
                 ("Pdo\\Sqlite" "OPEN_CREATE" 4)
                 ("Pdo\\Sqlite" "ATTR_READONLY_STATEMENT" 1001)
                 ("Pdo\\Sqlite" "ATTR_EXTENDED_RESULT_CODES" 1002)
                 ("Pdo\\Sqlite" "ATTR_BUSY_STATEMENT" 1003)
                 ("Pdo\\Sqlite" "ATTR_EXPLAIN_STATEMENT" 1004)
                 ("Pdo\\Sqlite" "EXPLAIN_MODE_PREPARED" 0)
                 ("Pdo\\Sqlite" "EXPLAIN_MODE_EXPLAIN" 1)
                 ("Pdo\\Sqlite" "EXPLAIN_MODE_EXPLAIN_QUERY_PLAN" 2)
                 ("Pdo\\Sqlite" "ATTR_TRANSACTION_MODE" 1005)
                 ("Pdo\\Sqlite" "TRANSACTION_MODE_DEFERRED" 0)
                 ("Pdo\\Sqlite" "TRANSACTION_MODE_IMMEDIATE" 1)
                 ("Pdo\\Sqlite" "TRANSACTION_MODE_EXCLUSIVE" 2)
                 ("Pdo\\Sqlite" "DETERMINISTIC" 2048)
                 ("Uri\\UriComparisonMode" "ExcludeFragment" :exclude-fragment)
                 ("Uri\\UriComparisonMode" "IncludeFragment" :include-fragment)))
  (destructuring-bind (class-name constant-name value) entry
    (%php-register-predefined-class-constant class-name constant-name value)))
