;;;; runtime-builtins-register-names.lisp — PHP builtin name table (first pass).
;;;;
;;;; Data, not logic: every entry maps a PHP function name to the Common Lisp
;;;; symbol that implements it. Read by %php-register-all-builtins in
;;;; runtime-builtins-register.lisp, which registers this table BEFORE seeding
;;;; the by-reference parameter registry.
;;;;
;;;; Entry order matters only where a name appears twice — the last
;;;; registration wins — so entries are appended rather than sorted.

(in-package :cl-cc/php)

(defparameter +php-builtin-name-table+
  ;; PHP builtin name -> Common Lisp implementation symbol, registered before
  ;; %PHP-SEED-BY-REF-PARAM-REGISTRY runs (that seeding call reads no state
  ;; this registry populates, but stays in its original relative position
  ;; below for behavior-preserving safety).
  '(
   ;; Core.
   ("count" . %php-count)
   ("sizeof" . %php-count)
   ("isset" . %php-isset)
   ("empty" . %php-empty)
   ("is_null" . %php-is-null)
   ("unset" . %php-unset)
   ("compact" . %php-compact)
   ("extract" . %php-extract)
   ("print_r" . %php-print-r)
   ("var_dump" . %php-var-dump)
   ("gettype" . %php-gettype)
   ("array_key_exists" . %php-builtin-array-key-exists)
   ;; String.
   ("strlen" . %php-strlen)
   ("strtolower" . %php-strtolower)
   ("strtoupper" . %php-strtoupper)
   ("str_replace" . %php-str-replace)
   ("str_ireplace" . %php-str-ireplace)
   ("substr" . %php-substr)
   ("trim" . %php-trim)
   ("ltrim" . %php-ltrim)
   ("rtrim" . %php-rtrim)
   ("explode" . %php-explode)
   ("implode" . %php-implode)
   ("join" . %php-join)
   ("strpos" . %php-strpos)
   ("stripos" . %php-stripos)
   ("strrpos" . %php-strrpos)
   ("str_contains" . %php-str-contains)
   ("str_starts_with" . %php-str-starts-with)
   ("str_ends_with" . %php-str-ends-with)
   ("strrev" . %php-strrev)
   ("str_repeat" . %php-str-repeat)
   ("sprintf" . %php-sprintf)
   ("htmlspecialchars" . %php-htmlspecialchars)
   ("str_pad" . %php-str-pad)
   ("str_split" . %php-str-split)
   ("substr_count" . %php-substr-count)
   ("substr_replace" . %php-substr-replace)
   ("ucfirst" . %php-ucfirst)
   ("lcfirst" . %php-lcfirst)
   ("ucwords" . %php-ucwords)
   ("ord" . %php-ord)
   ("chr" . %php-chr)
   ("bin2hex" . %php-bin2hex)
   ("hex2bin" . %php-hex2bin)
   ("strcmp" . %php-strcmp)
   ("strcasecmp" . %php-strcasecmp)
   ("strncmp" . %php-strncmp)
   ("strncasecmp" . %php-strncasecmp)
   ("strstr" . %php-strstr)
   ("stristr" . %php-stristr)
   ("strchr" . %php-strchr)
   ("str_word_count" . %php-str-word-count)
   ("levenshtein" . %php-levenshtein)
   ("grapheme_levenshtein" . %php-grapheme-levenshtein)
   ("similar_text" . %php-similar-text)
   ("soundex" . %php-soundex)
   ("printf" . %php-printf)
   ("vsprintf" . %php-vsprintf)
   ("vprintf" . %php-vprintf)
   ("nl2br" . %php-nl2br)
   ("wordwrap" . %php-wordwrap)
   ("chunk_split" . %php-chunk-split)
   ("html_entity_decode" . %php-html-entity-decode)
   ("strip_tags" . %php-strip-tags)
   ("addslashes" . %php-addslashes)
   ("stripslashes" . %php-stripslashes)
   ("base64_encode" . %php-base64-encode)
   ("base64_decode" . %php-base64-decode)
   ("md5" . %php-md5)
   ("sha1" . %php-sha1)
   ("crc32" . %php-crc32)
   ("urlencode" . %php-urlencode)
   ("urldecode" . %php-urldecode)
   ("rawurlencode" . %php-rawurlencode)
   ("rawurldecode" . %php-rawurldecode)
   ("json_encode" . %php-json-encode)
   ("json_decode" . %php-json-decode)
   ("mb_strlen" . %php-mb-strlen)
   ("mb_substr" . %php-mb-substr)
   ("mb_strtolower" . %php-mb-strtolower)
   ("mb_strtoupper" . %php-mb-strtoupper)
   ("mb_strpos" . %php-mb-strpos)
   ("mb_strrpos" . %php-mb-strrpos)
   ("mb_substr_count" . %php-mb-substr-count)
   ("mb_detect_encoding" . %php-mb-detect-encoding)
   ("mb_internal_encoding" . %php-mb-internal-encoding)
   ("mb_convert_encoding" . %php-mb-convert-encoding)
   ("mb_convert_case" . %php-mb-convert-case)
   ("mb_str_pad" . %php-mb-str-pad)
   ("mb_str_split" . %php-mb-str-split)
   ("str_getcsv" . %php-str-getcsv)
   ("mb_chr" . %php-mb-chr)
   ("mb_ord" . %php-mb-ord)
   ("mb_strimwidth" . %php-mb-strimwidth)
   ("mb_ereg" . %php-mb-ereg)
   ("mb_eregi" . %php-mb-eregi)
   ("mb_ereg_replace" . %php-mb-ereg-replace)
   ("mb_eregi_replace" . %php-mb-eregi-replace)
   ("mb_split" . %php-mb-split)
   ;; Additional string functions
   ("strtr" . %php-strtr)
   ("strpbrk" . %php-strpbrk)
   ("strspn" . %php-strspn)
   ("strcspn" . %php-strcspn)
   ("quotemeta" . %php-quotemeta)
   ("htmlentities" . %php-htmlentities)
   ("metaphone" . %php-metaphone)
   ;; HTML/encoding
   ("htmlspecialchars_decode" . %php-htmlspecialchars-decode)
   ("quoted_printable_encode" . %php-quoted-printable-encode)
   ("quoted_printable_decode" . %php-quoted-printable-decode)
   ;; JSON
   ("json_validate" . %php-json-validate)
   ;; ctype_* character classification
   ("ctype_alpha" . %php-ctype-alpha)
   ("ctype_digit" . %php-ctype-digit)
   ("ctype_alnum" . %php-ctype-alnum)
   ("ctype_space" . %php-ctype-space)
   ("ctype_upper" . %php-ctype-upper)
   ("ctype_lower" . %php-ctype-lower)
   ("ctype_punct" . %php-ctype-punct)
   ("ctype_graph" . %php-ctype-graph)
   ("ctype_print" . %php-ctype-print)
   ("ctype_xdigit" . %php-ctype-xdigit)
   ;; Type checks
   ("is_countable" . %php-is-countable)
   ;; Array.
   ("array_merge" . %php-array-merge)
   ("array_keys" . %php-array-keys)
   ("array_values" . %php-array-values)
   ("array_push" . %php-array-push)
   ("array_pop" . %php-array-pop)
   ("array_shift" . %php-array-shift)
   ("array_unshift" . %php-array-unshift)
   ("in_array" . %php-in-array)
   ("array_search" . %php-array-search)
   ("array_reverse" . %php-array-reverse)
   ("array_slice" . %php-array-slice)
   ("array_unique" . %php-array-unique)
   ("array_map" . %php-array-map)
   ("array_filter" . %php-array-filter)
   ("array_reduce" . %php-array-reduce)
   ("sort" . %php-sort)
   ("rsort" . %php-rsort)
   ("asort" . %php-asort)
   ("ksort" . %php-ksort)
   ("range" . %php-range)
   ("usort" . %php-usort)
   ("uasort" . %php-uasort)
   ("uksort" . %php-uksort)
   ("array_walk" . %php-array-walk)
   ("array_chunk" . %php-array-chunk)
   ("array_pad" . %php-array-pad)
   ("array_count_values" . %php-array-count-values)
   ("array_sum" . %php-array-sum)
   ("array_product" . %php-array-product)
   ("array_diff" . %php-array-diff)
   ("array_intersect" . %php-array-intersect)
   ("array_udiff" . %php-array-udiff)
   ("array_uintersect" . %php-array-uintersect)
   ("array_column" . %php-array-column)
   ("array_combine" . %php-array-combine)
   ("array_flip" . %php-array-flip)
   ("array_fill" . %php-array-fill)
   ("array_fill_keys" . %php-array-fill-keys)
   ("array_splice" . %php-array-splice)
   ("array_replace" . %php-array-replace)
   ("krsort" . %php-krsort)
   ("arsort" . %php-arsort)
   ("array_diff_key" . %php-array-diff-key)
   ("array_intersect_key" . %php-array-intersect-key)
   ("array_diff_assoc" . %php-array-diff-assoc)
   ("array_intersect_assoc" . %php-array-intersect-assoc)
   ("array_merge_recursive" . %php-array-merge-recursive)
   ("shuffle" . %php-shuffle)
   ("array_key_first" . %php-array-key-first)
   ("array_key_last" . %php-array-key-last)
   ("array_first" . %php-array-first)
   ("array_last" . %php-array-last)
   ("array_walk_recursive" . %php-array-walk-recursive)
   ("natsort" . %php-natsort)
   ("natcasesort" . %php-natcasesort)
   ("strnatcmp" . %php-strnatcmp)
   ("strnatcasecmp" . %php-strnatcasecmp)
   ;; Array sorts and extras.
   ("array_multisort" . %php-array-multisort)
   ;; list() — returns array for destructuring
   ("list" . %php-list-assign)
   ;; PHP 8.4 array functions.
   ("array_find" . %php-array-find)
   ("array_find_key" . %php-array-find-key)
   ("array_any" . %php-array-any)
   ("array_all" . %php-array-all)
   ;; PHP 8.1 Fiber builtins are registered in the late-loaded feature module.
   ;; after those functions are defined.
   ;; PHP Exception / Throwable helpers.
   ("set_exception_handler" . %php-set-exception-handler)
   ("class_implements" . %php-class-implements)
   ("class_parents" . %php-class-parents)
   ("class_uses" . %php-class-uses)
   ("spl_autoload_register" . %php-spl-autoload-register)
   ("spl_autoload_unregister" . %php-spl-autoload-unregister)
   ("spl_autoload_functions" . %php-spl-autoload-functions)
   ;; SPL data structures.
   ("SplStack" . %php-spl-stack)
   ("SplQueue" . %php-spl-queue)
   ("SplDoublyLinkedList" . %php-spl-doubly-linked-list)
   ("SplMinHeap" . %php-spl-min-heap)
   ("SplMaxHeap" . %php-spl-max-heap)
   ("SplFixedArray" . %php-spl-fixed-array)
   ;; Math.
   ("abs" . %php-abs)
   ("ceil" . %php-ceil)
   ("floor" . %php-floor)
   ("round" . %php-round)
   ("max" . %php-max)
   ("min" . %php-min)
   ("rand" . %php-rand)
   ("mt_rand" . %php-mt-rand)
   ("sqrt" . %php-sqrt)
   ("pow" . %php-pow)
   ("intdiv" . %php-intdiv)
   ("fdiv" . %php-fdiv)
   ("array_is_list" . %php-array-is-list)
   ("pi" . %php-pi)
   ("sin" . %php-sin)
   ("cos" . %php-cos)
   ("tan" . %php-tan)
   ("log" . %php-log)
   ("exp" . %php-exp)
   ("fmod" . %php-fmod)
   ("number_format" . %php-number-format)
   ("base_convert" . %php-base-convert)
   ("asin" . %php-asin)
   ("acos" . %php-acos)
   ("atan" . %php-atan)
   ("atan2" . %php-atan2)
   ("sinh" . %php-sinh)
   ("cosh" . %php-cosh)
   ("tanh" . %php-tanh)
   ("log10" . %php-log10)
   ("log2" . %php-log2)
   ("hypot" . %php-hypot)
   ("deg2rad" . %php-deg2rad)
   ("rad2deg" . %php-rad2deg)
   ("decbin" . %php-decbin)
   ("decoct" . %php-decoct)
   ("dechex" . %php-dechex)
   ("bindec" . %php-bindec)
   ("octdec" . %php-octdec)
   ("hexdec" . %php-hexdec)
   ("is_nan" . %php-is-nan)
   ("is_finite" . %php-is-finite)
   ("is_infinite" . %php-is-infinite)
   ("lcg_value" . %php-lcg-value)
   ("mt_srand" . %php-mt-srand)
   ("srand" . %php-srand)
   ;; Regex
   ("preg_match" . %php-preg-match)
   ("preg_match_all" . %php-preg-match-all)
   ("preg_replace" . %php-preg-replace)
   ("preg_split" . %php-preg-split)
   ("preg_quote" . %php-preg-quote)
   ("preg_replace_callback" . %php-preg-replace-callback)
   ("preg_replace_callback_array" . %php-preg-replace-callback-array)
   ;; Date/Time
   ("time" . %php-time)
   ("microtime" . %php-microtime)
   ("mktime" . %php-mktime)
   ("gmmktime" . %php-mktime)
   ("strtotime" . %php-strtotime)
   ("date" . %php-date)
   ("checkdate" . %php-checkdate)
   ("gmdate" . %php-gmdate)
   ("date_create" . %php-date-create)
   ("date_format" . %php-date-format)
   ("date_modify" . %php-date-modify)
   ("date_diff" . %php-date-diff)
   ("date_timestamp_get" . %php-date-timestamp)
   ("date_default_timezone_set" . %php-date-default-timezone-set)
   ("date_default_timezone_get" . %php-date-default-timezone-get)
   ;; Types and conversions.
   ("is_int" . %php-is-int)
   ("is_integer" . %php-is-integer)
   ("is_long" . %php-is-long)
   ("is_float" . %php-is-float)
   ("is_double" . %php-is-double)
   ("is_real" . %php-is-real)
   ("is_string" . %php-is-string)
   ("is_bool" . %php-is-bool)
   ("is_array" . %php-is-array)
   ("is_object" . %php-is-object)
   ("is_callable" . %php-is-callable)
   ("is_numeric" . %php-is-numeric)
   ("is_scalar" . %php-is-scalar)
   ("is_iterable" . %php-is-iterable)
   ("intval" . %php-intval)
   ("floatval" . %php-floatval)
   ("strval" . %php-strval)
   ("boolval" . %php-boolval)
   ("filter_var" . %php-filter-var)
   ("image_type_to_extension" . %php-image-type-to-extension)
   ("image_type_to_mime_type" . %php-image-type-to-mime-type)
   ("getimagesize" . %php-getimagesize)
   ("exif_imagetype" . %php-exif-imagetype)
   ("token_get_all" . %php-token-get-all)
   ("token_name" . %php-token-name)
   ("settype" . %php-settype)
    )
  "PHP builtin name -> Common Lisp implementation symbol.")
